Add set_option function

diff --git a/leo-install b/leo-install
--- a/leo-install
+++ b/leo-install
@@ -11,6 +11,7 @@ SCRIPT_VERSION=1.0
 LEO_DIR="/leoparx"
 BUILD_DIR=/root/custombuild
 VERSION_PACKAGES="packages.leo"
+BUILD_OPTIONS="build_options.leo"
 BUILD_SERVER="http://files.directadmin.com/services/custombuild"
 mkdir -p ${BUILD_DIR}
 chmod 700 ${BUILD_DIR}
@@ -63,6 +64,22 @@ if [ ! -d "${LEO_DIR}" ]; then
     chmod 755 ${LEO_DIR}
 fi
 
+# Check this script is running
+if [ -s ${BUILD_DIR}/leo.pid ]; then
+	pid=`cat ${BUILD_DIR}/leo.pid`
+	check_pid=`ps aux | awk '{print $2}' | grep ${pid}`
+
+	if [ "${check_pid}" != "" ] ; then
+		printf "This script may already be running in another process. Exiting.."
+        exit 1
+	else
+		echo $$ > ${BUILD_DIR}/leo.pid
+	fi
+else 
+	touch ${BUILD_DIR}/leo.pid
+	echo $$ > ${BUILD_DIR}/leo.pid
+fi
+
 # Common pre-install
 yum install -y wget tar gcc gcc-c++ flex bison make openssl openssl-devel perl quota libaio \
 libcom_err-devel libcurl-devel gd zlib-devel zip unzip libcap-devel cronie bzip2 cyrus-sasl-devel perl-ExtUtils-Embed \
@@ -72,8 +89,8 @@ psmisc net-tools systemd-devel libdb-devel perl-DBI perl-Perl4-CoreLibs perl-lib
 # Download source file function 
 get_file() {
     cd ${BUILD_DIR}
-    file_name=${1}
-    file_url="http://files.directadmin.com/services/custombuild/${file_name}"
+    local file_name=${1}
+    local file_url="http://files.directadmin.com/services/custombuild/${file_name}"
 
     if [ ! -s ${file_name} ]; then
         while true ; do
@@ -106,6 +123,40 @@ get_file() {
     fi
 }
 
+set_option() {
+    if [ -z "${3}" ]; then
+        echo "Three arguments are required for this function"
+        echo "set_option <option_name> <option_value> \"<options_valid>\""
+        return
+    fi
+
+    local opt_name=${1}
+    local opt_value=${2}
+    local valid_options=${3}
+
+    # Check option name 
+    local opt_line_number=`awk '{ print $0, NR }' ${BUILD_DIR}/${BUILT_OPTIONS}  | grep -m1 ${opt_name} | awk '{print $2}'`
+
+    if [ -z "${opt_line_number}" ]; then
+        echo "${opt_name} is not a valid option."
+        return
+    fi
+
+    # Check option value
+
+    for i in ${valid_options}; do
+        if [ ${opt_value} == ${i} ]; then
+            VALID_OPTION="yes"
+            # Replace to new option value
+            sed -i "${opt_line_number}s/.*/${opt_name}=${opt_value}/" ${BUILD_DIR}/${BUILT_OPTIONS}
+            
+            return
+        fi
+    done
+
+    echo "${opt_name}=${opt_value} is not a valid value."
+}
+
 init_version_packages() {
     cd ${BUILD_DIR}
     if [ ! -s ${BUILD_DIR}/${VERSION_PACKAGES} ]; then
@@ -126,7 +177,7 @@ init_version_packages() {
         done
     fi
 
-    source_versions=`awk -F ":" '{gsub(/\./,"_",$1);gsub(/-/,"_",$1);print "version_package_"$1"="$2}' ./${VERSION_PACKAGES}`
+    local source_versions=`awk -F ":" '{gsub(/\./,"_",$1);gsub(/-/,"_",$1);print "version_package_"$1"="$2}' ./${VERSION_PACKAGES}`
     eval ${source_versions}
 }
 
